### ISSUE TITLE
Unable to run the engine

### ISSUE THREAD

**Issue by umairq** [gmontoya/federatedOptimizer#2] opened 2019-02-11 04:14 UTC
Hi @gmontoya 
We tried to run the engine using the instructions you have provided in readme file, but it seems it is still missing some files. Because when we try to run script: ./executeQueriesOdyssey.sh, we get the 0 results for every query without giving any error, 
we tried to output the error it says: 

> line 74: [: : integer expression expected

When we generate statistics, we get the following output:

> `generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
Number of leaves: 0
0.22 92% 0 34756
obtainHierarchicalCharacterization
finished with Drugbank
generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
Number of leaves: 0
0.35 69% 0 34648
obtainHierarchicalCharacterization
addInterDatasetLinksRTreeOne NYTimes Drugbank
0.15 96% 0 31672
addInterDatasetCSsRTreeOne NYTimes Drugbank
0.16 92% 0 31732
finished with NYTimes
generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
Number of leaves: 0
0.20 91% 0 34776
obtainHierarchicalCharacterization
addInterDatasetLinksRTreeOne LMDB Drugbank
0.16 93% 0 31672
addInterDatasetCSsRTreeOne LMDB Drugbank
0.16 92% 0 31688
addInterDatasetLinksRTreeOne LMDB NYTimes
0.15 95% 0 31668
addInterDatasetCSsRTreeOne LMDB NYTimes
0.15 96% 0 31676
finished with LMDB
generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
Number of leaves: 0
0.20 91% 0 34844
obtainHierarchicalCharacterization
addInterDatasetLinksRTreeOne Geonames Drugbank
0.17 92% 0 31792
addInterDatasetCSsRTreeOne Geonames Drugbank
0.16 93% 0 31596
addInterDatasetLinksRTreeOne Geonames NYTimes
0.29 93% 0 31600
addInterDatasetCSsRTreeOne Geonames NYTimes
0.16 92% 0 31680
addInterDatasetLinksRTreeOne Geonames LMDB
0.16 93% 0 31572
addInterDatasetCSsRTreeOne Geonames LMDB
0.15 94% 0 31744
finished with Geonames
generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
Number of leaves: 0
0.21 91% 0 34256
obtainHierarchicalCharacterization
addInterDatasetLinksRTreeOne DBpedia Drugbank
0.15 95% 0 31320
addInterDatasetCSsRTreeOne DBpedia Drugbank
0.15 95% 0 31604
addInterDatasetLinksRTreeOne DBpedia NYTimes
0.14 95% 0 31584
addInterDatasetCSsRTreeOne DBpedia NYTimes
0.24 90% 0 31220
addInterDatasetLinksRTreeOne DBpedia LMDB
0.16 93% 0 31720
addInterDatasetCSsRTreeOne DBpedia LMDB
0.16 93% 0 31752
addInterDatasetLinksRTreeOne DBpedia Geonames
0.15 94% 0 31796
addInterDatasetCSsRTreeOne DBpedia Geonames
0.14 95% 0 31120
finished with DBpedia
`

I tried to run sortDataset.sh script before generateStatistics script, but it says it needs some input files like "{dataset}*_sorted" 

> ls: cannot access 'DBpedia*_sorted': No such file or directory

If this is the problem, what should we put in this directory or file? If we need to provide all triples of the dataset, how can we generate? 

Can you please specify the steps and missing files for running the engine?

------
thanks
Regards

**Comment by gmontoya** [comment] 2019-02-15 08:32
Based on your description and the output you showed, it seems that no statistics were generated at all. If the program actually printed that the generated trees have 0 leaves as shown in the output you posted, then the system does not find any statistics to work with. But it is not completely clear to me what you actually did prior to running a query.
 
Regarding the error “line 74: [: : integer expression expected”, it seems that expected outputs from an appropriate execution are missing because Odyssey does not have statistics to work with. Examples of the expected outputs are the planning and execution time. 
 
My best guess regarding what went wrong during the creation of the statistics is that the paths to the local folder containing the datasets in generateStatistics.sh were not set correctly. In generateStatistics.sh you need to adapt lines 12, 14, 17, 18, 21, 22, 24, 29, 32 and 34. In our case we had the datasets at /home/roott/fedBenchData and, as explained in the README, this folder has a subfolder for each of the datasets (ChEBI, KEGG, Drugbank, Jamendo, NYTimes, SWDF, LMDB, Geonames, DBpedia), and inside the subfolders files with all the triples in each dataset are available, the files are assumed to be ChEBI/chebiSorted.n3, ..., DBpedia/dbpediaSorted.n3 if they are sorted by subject or ChEBI/chebi.n3, ..., DBpedia/dbpedia.n3 if the triples are not sorted by subject. 
 
The output that you posted from the generation of statistics is difficult to read, somehow it seems like one very long line that was obtained as output. When I execute the generation of statistics, the obtained output has 207 lines and the three first lines are as follows:
generateStatistics
mergeCharacteristicSetsPlus
obtainRadixOneBasedIndex
…
This output was printed just to be aware of the progress of the computation of statistics and measure the time taken by each part of the process. More informative error messages should be included in the “error” and “output” files generated in the folder “code” if anything went wrong in any of the steps in the computation, for example if something when wrong when executing the program mergeCharacteristicSetsPlus.java for the DBpedia dataset this information is registered in the file code/errorMergeCharacteristicSetsPlusDBpedia. 
The numbers for time in the output you posted are suspiciously low. This is another indicator that the statistics were not correctly generated.
 
You could also check the weights of the files that are generated, for instance the file DBpedia/statisticsDBpedia_rtree_100_10_reduced10000CS_1 should weight around 70MB (we gave numbers like this one in our article: “The Odyssey Approach for Optimizing Federated SPARQL Queries” available at https://iswc2017.semanticweb.org/wp-content/uploads/papers/MainProceedings/204.pdf).
 
The generateStatistics.sh script assumes as input datasets with triples sorted by subject. As stated in the README, if they are not sorted, you should run sortDataset.sh to sort them. In the script sortDataset.sh you need to change the value of the variable "folder" to the location of a folder on your machine that contains the datasets. The reason why you obtain the error message mentioning DBpedia when running this script is that the folder variable references a local path to the dataset, in our case it was "$folder/DBpedia/dbpedia.n3" or "$folder/DBpedia/dbpediaSorted.n3" depending on the triples being already sorted or not. In the case of this file, you need to change the lines 5-7 and 12 (I have commented out some lines that are not necessary for the expected use of this script when preparing the files for the computation of statistics).
 
Once you have obtained the statistics, you can proceed as described in the README file, and set the variable fedBenchDataPath in the file federatedOptimizer/scripts/executeQueriesOdyssey.sh to the path of the folder that contains the statistics used by Odyssey.
 
I hope everything is clearer now and that the statistics will be generated correctly and the queries will be properly executed by Odyssey. 
In case there are still some problems, please let me know and provide relevant details regarding the scripts you have executed, the changes you have made, the size of the generated files and the information in any output or error file generated during the computation.

**Comment by umairq** [comment] 2019-02-20 01:31
Thankyou for your detailed reply @gmontoya 
Based on your reply and readme file I figured out that I was missing sorting based on subjects. 
However, When i run sortdataset.sh script on small datasets like LMDB etc it works perfectly fine, but when i run on large datasets like dbpedia, Geonames it gives
 "java.lang.OutOfMemoryError: Java heap space" Exception. I tried to increase heap space then it gives some other exception 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
	at java.base/java.lang.String.substring(String.java:1873)
	at orderDataset.main(orderDataset.java:40)

Please help me to figure out this issue, thanks

**Comment by umairq** [comment] 2019-02-22 06:23
Thankyou for your time and response @gmontoya . I just fixed the problem after running the sorting datasets script on  server machine with high specifications.
It is running now.
Thankyou
Regards
Umair

**Comment by gmontoya** [comment] 2019-02-22 13:42
It is good to know that you fixed the problem, but I will answer your previous message in case such issue occurs again. 

The current version of sortDatasets.sh is very simple and may incur in an OutOfMemoryError as you mentioned. 
If the machine you are using has enough main memory to allow for the dataset to be loaded in memory, the simple version is better. 

As an alternative, the dataset can be divided into smaller subsets that are sorted independently and the sorted parts can be merged together using mergeDataset.java.
In the current version of sortDatasets.sh, this alternative option is commented out. The value of ‘m’ represents the number of lines that each part of the dataset can have and it should be set according to the amount of main memory available. 

According to the information you posted, the StringIndexOutOfBoundException exception is produced by the execution of the code in line 40 of orderDataset.java. It looks like you were able to run our code on some datasets but encountered a parser/encoding error with Geonames, which suggests that the data in that file is structured differently than other datasets. 

Line 40 obtains the substring from the start of the line until the first space. If line 40 is causing this exception, it means that the dataset you are parsing has at least one line where there is no such space. 

orderDataset.java works well if there is one line per triple in the dataset and the subject and predicate are separated by one space and the predicate and object are separated by one space (lines 39-44). Any blank line, line with comments or line with any other type of separation between the different parts of the triples will not comply with what is expected. 

To solve this problem, you could either make the input file comply with the expected format or adapt orderDataset.java to support the particularities of the file you are passing to it. The changes to orderDataset.java will likely include skipping irrelevant lines and considering alternative ways to the separate the components of a triple.

**Comment by umairq** [comment] 2019-02-25 11:15
Thanks a lot for explaining the solution @gmontoya , I have done it by changing the dataset format to comply with your orderDataset.java class. 
I had just one more question, when I want to calculate the number of transferred tuples by executing the script executeQueriesOdysseyWithProxies.sh, I always get 0 as answer for transferred tuples.  rest query answer is correct. I have modified following files:
startProxies2.sh
startOneProxy2.sh
executeQueriesOdysseyWithProxies.sh
and compiled the java class in proxy folder.
I have changed address to my endpoint address and proxy address to localhost. similarly for ports as well.
I am not getting any error but only zero as answer like following:
q1 7 7 0 1404 0 0 90
is there anything I am missing?

Thanks
Regards

**Comment by umairq** [comment] 2019-02-25 23:44
I have fixed this issue as well, What I was missing is I have to put proxy port and IP in federation file as well.
I would suggest, It is better to specify these minor things in readme file as well(for non-experts).
Thankyou.
Regards
Umair

**Comment by gmontoya** [comment] 2019-03-01 13:02
It is good to know that you were able to run the experiments using proxies. 
There are a few things to mention regarding the use of proxies.

The scripts startProxies2.sh and startOneProxy2.sh are designed to consider endpoints available at different hosts. 

The changes to executeQueriesOdysseyWithProxies.sh should include:
1. set the variables 'ODYSSEY_HOME', 'JENA_HOME', 'fedBenchDataPath', 'fedBench' as in the case without proxies (executeQueriesOdyssey.sh)
2. set the variable 'proxyFederationFile' to a valid path in your computer for a new file to store the information of the started proxies, it should be the same as in startProxies2.sh
3. set the variable 'datasets' to a file that indicates for each dataset the address of the proxy, in our case we used localhost with port numbers start from port number 3030, the initial port is passed in line 42 to the script startProxies2.sh 
4. change line 42 to include the actual addresses of the endpoints and starting port to use for the proxies (this should be consistent with the information in the file described in the previous point)

Additionally:
5. check that the variable 'ODYSSEY_HOME' has been correctly set to use it in startOneProxy2.sh
6. the variable dataConfig declared in line 240 in evaluateSPARQLQuery.java has as value the path of a file with the description of the federation for FedX, in this federation the addresses of the proxies should be included (instead of the addresses of the endpoints). In our case, instead of modifying the source code, we opted for copying the relevant file (for instance the one that uses proxies instead of the endpoints) to the path mentioned in line 240 of the file evaluateSPARQLQuery.java.

Not doing 2, 3, or 6 could lead to the problem you mentioned of having zero as the number of transferred tuples and number of calls.

**Comment by umairq** [comment] 2019-03-04 07:18
Hi @gmontoya 
Thanks for the reply. I ran the proxies for odyssey successfully, one problem that I am facing is that when I try to run same proxy for the other query engines like costfed and LHD I got the following error:

`Caused by: com.fluidops.fedx.exception.OptimizationException: com.fluidops.fedx.exception.OptimizationException: Error checking results for endpoint sparql_localhost:3029_sparql: @ sparql_localhost:3029_sparql - Server responded with an unsupported file format: text/html. Subquery: ASK {<http://dbpedia.org/resource/Barack_Obama> ?predicate ?object .  }`

If you can help that would be great
thanks in advance
Regards

**Comment by gmontoya** [comment] 2019-03-04 14:24
I would suggest to check that the different descriptions of the federation given to the federated query engine are consistent, i.e., the same address and port are used for the same dataset. 

Two possible issues in the error you posted:
- It seems that a proxy on port 3029 is used, but in the federation we used in our experiments we had proxies only in ports 3030 until 3038.
- The "unsupported file format" message suggests that the federated query engines or the endpoints do not support the same formats.

To check if the last point is the cause of the error, I would suggest to execute the same query with the same federated query engine and the federation of endpoints (without the proxies).

As you have succeeded in using Odyssey with and without proxies, I will proceed to close this issue.

**Closed by gmontoya** 2019-03-04 14:24 UTC
